ruby_image: &ruby_image
              circleci/ruby:2.7.2-node-browsers-legacy

cache_key: &cache_key
             cache-{{ checksum "Gemfile.lock" }}

version: 2.1
jobs:
  build:
    docker:
      - image: *ruby_image
        environment:
          RAILS_ENV: test
          DATABASE_URL: "postgres://voice_origami@localhost:5432/voice_origami_test"
      - image: postgres:12.4-alpine
        environment:
          POSTGRES_HOST_AUTH_METHOD: 'trust'
          POSTGRES_USER: voice_origami
          POSTGRES_DB: voice_origami_test
    working_directory: ~/voice_origami
    steps:
      - checkout
      - run: gem update bundler
      - restore_cache:
          key: *cache_key
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: *cache_key
          paths:
            - vendor/bundle
      - run: bundle exec rake db:migrate:reset db:seed
      - run:
          name: yarn  Install
          command: yarn install
      - run: bundle exec bin/webpack
      - run: bundle exec rspec --format documentation
      - store_test_results:
          path: test_results

workflows:
  version: 2.1

  build-and-deploy:
    jobs:
      - build